name: Twitter Post

on:
  repository_dispatch:
    types: [on-demand-twit]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f req_main_twit.txt ]; then pip install -r req_main_twit.txt; fi
    - name: Run script
      run: |
        python main_twit.py
      env:
        CONSUMER_KEY: ${{ secrets.NEWS_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.NEWS_CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.NEWS_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.NEWS_ACCESS_TOKEN_SECRET }}
