name: Python application

on:
  repository_dispatch:
    types: [on-demand-test]
#  schedule:
#    - cron:  '30 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: |
        python main.py
      env:
        CONSUMER_KEY: ${{ secrets.NEWS_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.NEWS_CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.NEWS_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.NEWS_ACCESS_TOKEN_SECRET }}
